#!/usr/bin/env sh
set -eu

python3 - <<'PY' > requirements.txt
from pathlib import Path
import tomllib

project = tomllib.loads(Path("pyproject.toml").read_text())
dependencies = project["project"]["dependencies"]

print("# Autogenerated from pyproject.toml")
for dependency in dependencies:
    print(dependency)
PY
