from __future__ import annotations

from PyQt6.QtCore import QObject, pyqtSignal


DEFAULT_LOCALE = "pt-BR"
FALLBACK_LOCALE = "en"
SUPPORTED_LOCALES = ("pt-BR", "en")

TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "app.name": "ContExt",
        "window.title": "ContExt | PyQt6 Graph",
        "menu.file": "File",
        "menu.edit": "Edit",
        "menu.view": "View",
        "menu.language": "Language",
        "menu.node_category.input": "Input",
        "menu.node_category.processing": "Processing",
        "menu.node_category.filtering": "Filtering",
        "menu.node_category.frequency": "Frequency",
        "menu.node_category.thresholding": "Thresholding",
        "menu.node_category.output": "Output",
        "toolbar.main": "Main",
        "action.open_pipeline": "Open Pipeline...",
        "action.save_pipeline": "Save Pipeline...",
        "action.save_preview": "Save Preview as PNG...",
        "action.save_histogram": "Save Histogram as PNG...",
        "action.open_image": "Open Image...",
        "action.delete_selected": "Delete Selected",
        "action.quit": "Quit",
        "dock.properties": "Properties",
        "dock.preview": "Preview",
        "dock.histogram": "Histogram",
        "dialog.open_pipeline.title": "Open Pipeline",
        "dialog.open_pipeline.filter": "Context Pipeline (*.ctxp *.json)",
        "dialog.save_pipeline.title": "Save Pipeline",
        "dialog.save_pipeline.filter": "Context Pipeline (*.ctxp);;JSON (*.json)",
        "dialog.save_preview.title": "Save Preview as PNG",
        "dialog.save_preview.filter": "PNG Image (*.png)",
        "dialog.save_histogram.title": "Save Histogram as PNG",
        "dialog.save_histogram.filter": "PNG Image (*.png)",
        "dialog.open_image.title": "Open Image",
        "dialog.open_image.filter": "Images (*.png *.jpg *.jpeg *.bmp *.tif *.tiff)",
        "status.loaded_image": "Loaded {name}",
        "status.loaded_pipeline": "Loaded pipeline {name}",
        "status.saved_pipeline": "Saved pipeline {name}",
        "status.saved_preview": "Saved preview {name}",
        "status.saved_histogram": "Saved histogram {name}",
        "status.processing": "Processing graph...",
        "status.ready": "Ready",
        "status.theme_enabled": "{theme} enabled",
        "status.language_enabled": "Language set to {language}",
        "theme.name.material_light": "Material Light",
        "theme.name.material_dark": "Material Dark",
        "language.name.pt-BR": "Portuguese (Brazil)",
        "language.name.en": "English",
        "graph.menu.add_source": "Add Source",
        "graph.menu.add_blur": "Add Blur",
        "graph.menu.add_preview": "Add Preview",
        "graph.menu.delete_selected": "Delete Selected",
        "graph.error.only_one_source": "Only one Source node is allowed.",
        "graph.error.only_one_preview": "Only one Preview node is allowed.",
        "graph.error.unsupported_node_type": "Unsupported node type: {type_name}.",
        "graph.error.connection_self": "A node cannot connect to itself.",
        "graph.error.connection_cycle": "This connection would create a cycle.",
        "graph.error.connection_input_occupied": "That input already has a connection.",
        "graph.error.connection_unknown_node": "The selected node is no longer available.",
        "graph.error.connection_invalid_port": "The selected ports are not compatible.",
        "graph.error.connection_rejected": "This connection is not valid.",
        "graph.error.only_one_singleton": "Only one {title} node is allowed.",
        "graph.error.pipeline_load_failed": "Failed to open pipeline. {message}",
        "graph.error.pipeline_save_failed": "Failed to save pipeline. {message}",
        "panel.none.title": "No node selected",
        "panel.none.description": "Select a node to edit its properties.",
        "panel.source.description": "Loads the working image into the pipeline.",
        "panel.source.path": "Path",
        "panel.source.resolution": "Resolution",
        "panel.source.no_image": "No image loaded",
        "panel.crop.description": "Crops the incoming image using pixel coordinates. Zero end values mean full size.",
        "panel.histogram_equalization.description": "Equalizes the luminance histogram of the incoming image.",
        "panel.clahe_equalization.description": "Applies CLAHE to the luminance channel with configurable clip limit and tile size.",
        "panel.brightness_contrast.description": "Adjusts brightness and contrast using scale and offset.",
        "panel.blur.description": "Applies a Gaussian blur to the incoming image. You can also scrub it inside the node.",
        "panel.blur.kernel_size": "Kernel size",
        "panel.average_blur.description": "Applies a normalized box blur to the incoming image.",
        "panel.gaussian_blur.description": "Applies a Gaussian blur to the incoming image.",
        "panel.median_blur.description": "Applies a median blur to the incoming image.",
        "panel.gabor_filter.description": "Runs a configurable Gabor filter over the grayscale version of the image.",
        "panel.frequency_domain_filter.description": "Filters the grayscale FFT using low-pass, high-pass, band-pass, or band-stop masks.",
        "panel.grayscale.description": "Converts the image to grayscale, optionally excluding source channels first.",
        "panel.laplacian.description": "Computes the Laplacian response of the incoming image.",
        "panel.sobel.description": "Computes Sobel gradients along the selected axis.",
        "panel.global_threshold.description": "Applies a global threshold with optional inversion.",
        "panel.adaptive_mean_threshold.description": "Applies adaptive mean thresholding with the same defaults used in the main branch.",
        "panel.adaptive_gaussian_threshold.description": "Applies adaptive Gaussian thresholding with the same defaults used in the main branch.",
        "panel.otsu_binarization.description": "Applies Otsu binarization over the grayscale image.",
        "panel.preview.description": "Displays the last image flowing through the graph.",
        "panel.preview.status": "Status",
        "panel.preview.waiting": "Waiting for input",
        "panel.preview.ready": "Ready",
        "preview.unavailable": "Preview unavailable",
        "preview.export.unavailable": "There is no preview image to save yet.",
        "histogram.unavailable": "Histogram unavailable",
        "histogram.export.unavailable": "There is no histogram to save yet.",
        "histogram.action.export": "Export Histogram...",
        "node.source.title": "Source",
        "node.source.body.empty": "Load an image",
        "node.source.body.ready": "Image ready",
        "node.crop.title": "Crop",
        "node.crop.body": "Pixel crop",
        "node.histogram_equalization.title": "Histogram EQ",
        "node.histogram_equalization.body": "Luminance equalization",
        "node.clahe_equalization.title": "CLAHE",
        "node.clahe_equalization.body": "Adaptive equalization",
        "node.brightness_contrast.title": "Brightness / Contrast",
        "node.brightness_contrast.body": "Scale and offset",
        "node.average_blur.title": "Average Blur",
        "node.average_blur.body": "Box filter",
        "node.gaussian_blur.title": "Gaussian Blur",
        "node.gaussian_blur.body": "Gaussian smoothing",
        "node.blur.title": "Blur",
        "node.blur.body": "Gaussian blur",
        "node.median_blur.title": "Median Blur",
        "node.median_blur.body": "Median smoothing",
        "node.gabor_filter.title": "Gabor Filter",
        "node.gabor_filter.body": "Oriented texture response",
        "node.frequency_domain_filter.title": "FFT Filter",
        "node.frequency_domain_filter.body": "Frequency mask",
        "node.frequency_domain_filter.preview": "Frequency domain",
        "node.frequency_domain_filter.preview.unavailable": "Awaiting spectrum",
        "node.grayscale.title": "Grayscale",
        "node.grayscale.body": "Channel-aware grayscale",
        "node.laplacian.title": "Laplacian",
        "node.laplacian.body": "Second derivative",
        "node.sobel.title": "Sobel",
        "node.sobel.body": "Edge gradient",
        "node.global_threshold.title": "Global Threshold",
        "node.global_threshold.body": "Binary cutoff",
        "node.adaptive_mean_threshold.title": "Adaptive Mean",
        "node.adaptive_mean_threshold.body": "Local threshold",
        "node.adaptive_gaussian_threshold.title": "Adaptive Gaussian",
        "node.adaptive_gaussian_threshold.body": "Weighted local threshold",
        "node.otsu_binarization.title": "Otsu",
        "node.otsu_binarization.body": "Automatic threshold",
        "node.preview.title": "Preview",
        "node.preview.body": "Canvas output",
        "node.preview.action.save": "Save Preview\nas PNG...",
        "node.status.ready": "READY",
        "node.status.wait": "WAIT",
        "param.kernel_size": "Kernel",
        "param.crop.start_x": "Start X",
        "param.crop.start_y": "Start Y",
        "param.crop.end_x": "End X",
        "param.crop.end_y": "End Y",
        "param.clahe.clip_limit": "Clip limit",
        "param.clahe.tile_grid_size": "Tile grid",
        "param.brightness_contrast.brightness": "Brightness",
        "param.brightness_contrast.contrast": "Contrast",
        "param.gabor.kernel_size": "Kernel",
        "param.gabor.sigma": "Sigma",
        "param.gabor.theta_deg": "Theta (deg)",
        "param.gabor.lambda_value": "Lambda",
        "param.gabor.gamma": "Gamma",
        "param.gabor.psi_deg": "Psi (deg)",
        "param.frequency.mode": "Mode",
        "param.frequency.mode.none": "None",
        "param.frequency.mode.low_pass": "Low-pass",
        "param.frequency.mode.high_pass": "High-pass",
        "param.frequency.mode.band_pass": "Band-pass",
        "param.frequency.mode.band_stop": "Band-stop",
        "param.frequency.cutoff": "Cutoff",
        "param.frequency.band_min": "Band min",
        "param.frequency.band_max": "Band max",
        "param.grayscale.exclude_red": "Exclude red",
        "param.grayscale.exclude_green": "Exclude green",
        "param.grayscale.exclude_blue": "Exclude blue",
        "param.sobel.axis": "Axis",
        "param.sobel.axis.x_axis": "X axis",
        "param.sobel.axis.y_axis": "Y axis",
        "param.sobel.axis.xy_axis": "XY axes",
        "param.global_threshold.threshold": "Threshold",
        "param.global_threshold.invert": "Invert",
        "startup.title": "Start a Project",
        "startup.subtitle": "Create a new graph or open an existing .ctxp pipeline.",
        "startup.new_project": "New Project",
        "startup.open_project": "Open Project...",
        "startup.close": "Close",
        "startup.version": "Version {version}",
        "startup.select_theme": "Theme",
        "startup.select_language": "Preferred language",
        "startup.continue": "Continue",
        "startup.wait": "Loading components...",
        "startup.auto_continue": "Ready. Opening automatically...",
        "startup.click_continue": "Ready. Click continue to enter the app.",
        "startup.step.preferences": "Loading preferences",
        "startup.step.theme": "Applying theme",
        "startup.step.locale": "Applying language",
        "startup.step.workspace": "Building workspace",
        "startup.ready": "Everything is ready",
    },
    "pt-BR": {
        "app.name": "ContExt",
        "window.title": "ContExt | Grafo PyQt6",
        "menu.file": "Arquivo",
        "menu.edit": "Editar",
        "menu.view": "Visual",
        "menu.language": "Idioma",
        "menu.node_category.input": "Entrada",
        "menu.node_category.processing": "Processamento",
        "menu.node_category.filtering": "Filtragem",
        "menu.node_category.frequency": "Frequência",
        "menu.node_category.thresholding": "Limiarização",
        "menu.node_category.output": "Saída",
        "toolbar.main": "Principal",
        "action.open_pipeline": "Abrir pipeline...",
        "action.save_pipeline": "Salvar pipeline...",
        "action.save_preview": "Salvar preview como PNG...",
        "action.save_histogram": "Salvar histograma como PNG...",
        "action.open_image": "Abrir imagem...",
        "action.delete_selected": "Excluir seleção",
        "action.quit": "Sair",
        "dock.properties": "Propriedades",
        "dock.preview": "Pré-visualização",
        "dock.histogram": "Histograma",
        "dialog.open_pipeline.title": "Abrir pipeline",
        "dialog.open_pipeline.filter": "Pipeline Context (*.ctxp *.json)",
        "dialog.save_pipeline.title": "Salvar pipeline",
        "dialog.save_pipeline.filter": "Pipeline Context (*.ctxp);;JSON (*.json)",
        "dialog.save_preview.title": "Salvar preview como PNG",
        "dialog.save_preview.filter": "Imagem PNG (*.png)",
        "dialog.save_histogram.title": "Salvar histograma como PNG",
        "dialog.save_histogram.filter": "Imagem PNG (*.png)",
        "dialog.open_image.title": "Abrir imagem",
        "dialog.open_image.filter": "Imagens (*.png *.jpg *.jpeg *.bmp *.tif *.tiff)",
        "status.loaded_image": "Imagem carregada: {name}",
        "status.loaded_pipeline": "Pipeline carregada: {name}",
        "status.saved_pipeline": "Pipeline salva: {name}",
        "status.saved_preview": "Preview salvo: {name}",
        "status.saved_histogram": "Histograma salvo: {name}",
        "status.processing": "Processando grafo...",
        "status.ready": "Pronto",
        "status.theme_enabled": "{theme} ativado",
        "status.language_enabled": "Idioma alterado para {language}",
        "theme.name.material_light": "Material Claro",
        "theme.name.material_dark": "Material Escuro",
        "language.name.pt-BR": "Português (Brasil)",
        "language.name.en": "Inglês",
        "graph.menu.add_source": "Adicionar Source",
        "graph.menu.add_blur": "Adicionar Blur",
        "graph.menu.add_preview": "Adicionar Preview",
        "graph.menu.delete_selected": "Excluir seleção",
        "graph.error.only_one_source": "Somente um node Source é permitido.",
        "graph.error.only_one_preview": "Somente um node Preview é permitido.",
        "graph.error.unsupported_node_type": "Tipo de node não suportado: {type_name}.",
        "graph.error.connection_self": "Um node não pode se conectar a si mesmo.",
        "graph.error.connection_cycle": "Essa conexão criaria um ciclo.",
        "graph.error.connection_input_occupied": "Essa entrada já possui uma conexão.",
        "graph.error.connection_unknown_node": "O node selecionado não está mais disponível.",
        "graph.error.connection_invalid_port": "As portas selecionadas não são compatíveis.",
        "graph.error.connection_rejected": "Essa conexão não é válida.",
        "graph.error.only_one_singleton": "Somente um node {title} é permitido.",
        "graph.error.pipeline_load_failed": "Falha ao abrir a pipeline. {message}",
        "graph.error.pipeline_save_failed": "Falha ao salvar a pipeline. {message}",
        "panel.none.title": "Nenhum node selecionado",
        "panel.none.description": "Selecione um node para editar as propriedades.",
        "panel.source.description": "Carrega a imagem de trabalho para dentro do pipeline.",
        "panel.source.path": "Caminho",
        "panel.source.resolution": "Resolução",
        "panel.source.no_image": "Nenhuma imagem carregada",
        "panel.crop.description": "Recorta a imagem de entrada usando coordenadas em pixels. Valores finais zero significam tamanho total.",
        "panel.histogram_equalization.description": "Equaliza o histograma de luminância da imagem de entrada.",
        "panel.clahe_equalization.description": "Aplica CLAHE ao canal de luminância com limite de clip e grade configuráveis.",
        "panel.brightness_contrast.description": "Ajusta brilho e contraste usando ganho e deslocamento.",
        "panel.blur.description": "Aplica um desfoque gaussiano na imagem de entrada. Você também pode ajustar isso dentro do node.",
        "panel.blur.kernel_size": "Tamanho do kernel",
        "panel.average_blur.description": "Aplica um desfoque médio normalizado na imagem de entrada.",
        "panel.gaussian_blur.description": "Aplica um desfoque gaussiano na imagem de entrada.",
        "panel.median_blur.description": "Aplica um desfoque mediano na imagem de entrada.",
        "panel.gabor_filter.description": "Executa um filtro de Gabor configurável sobre a versão em escala de cinza da imagem.",
        "panel.frequency_domain_filter.description": "Filtra a FFT em escala de cinza usando máscaras passa-baixa, passa-alta, passa-faixa ou rejeita-faixa.",
        "panel.grayscale.description": "Converte a imagem para escala de cinza, opcionalmente excluindo canais antes.",
        "panel.laplacian.description": "Calcula a resposta Laplaciana da imagem de entrada.",
        "panel.sobel.description": "Calcula gradientes de Sobel no eixo selecionado.",
        "panel.global_threshold.description": "Aplica um limiar global com inversão opcional.",
        "panel.adaptive_mean_threshold.description": "Aplica limiarização adaptativa por média com os mesmos defaults da branch principal.",
        "panel.adaptive_gaussian_threshold.description": "Aplica limiarização adaptativa gaussiana com os mesmos defaults da branch principal.",
        "panel.otsu_binarization.description": "Aplica binarização de Otsu sobre a imagem em escala de cinza.",
        "panel.preview.description": "Exibe a imagem final que chega ao grafo.",
        "panel.preview.status": "Status",
        "panel.preview.waiting": "Aguardando entrada",
        "panel.preview.ready": "Pronto",
        "preview.unavailable": "Pré-visualização indisponível",
        "preview.export.unavailable": "Ainda não existe uma imagem de preview para salvar.",
        "histogram.unavailable": "Histograma indisponível",
        "histogram.export.unavailable": "Ainda não existe um histograma para salvar.",
        "histogram.action.export": "Exportar histograma...",
        "node.source.title": "Source",
        "node.source.body.empty": "Carregue uma imagem",
        "node.source.body.ready": "Imagem pronta",
        "node.crop.title": "Crop",
        "node.crop.body": "Recorte por pixels",
        "node.histogram_equalization.title": "Histograma EQ",
        "node.histogram_equalization.body": "Equalização de luminância",
        "node.clahe_equalization.title": "CLAHE",
        "node.clahe_equalization.body": "Equalização adaptativa",
        "node.brightness_contrast.title": "Brilho / Contraste",
        "node.brightness_contrast.body": "Ganho e deslocamento",
        "node.average_blur.title": "Average Blur",
        "node.average_blur.body": "Filtro caixa",
        "node.gaussian_blur.title": "Gaussian Blur",
        "node.gaussian_blur.body": "Suavização gaussiana",
        "node.blur.title": "Blur",
        "node.blur.body": "Desfoque gaussiano",
        "node.median_blur.title": "Median Blur",
        "node.median_blur.body": "Suavização mediana",
        "node.gabor_filter.title": "Gabor Filter",
        "node.gabor_filter.body": "Resposta de textura orientada",
        "node.frequency_domain_filter.title": "Filtro FFT",
        "node.frequency_domain_filter.body": "Máscara de frequência",
        "node.frequency_domain_filter.preview": "Domínio da frequência",
        "node.frequency_domain_filter.preview.unavailable": "Aguardando espectro",
        "node.grayscale.title": "Grayscale",
        "node.grayscale.body": "Cinza por canais",
        "node.laplacian.title": "Laplacian",
        "node.laplacian.body": "Segunda derivada",
        "node.sobel.title": "Sobel",
        "node.sobel.body": "Gradiente de borda",
        "node.global_threshold.title": "Global Threshold",
        "node.global_threshold.body": "Corte binário",
        "node.adaptive_mean_threshold.title": "Adaptive Mean",
        "node.adaptive_mean_threshold.body": "Limiar local",
        "node.adaptive_gaussian_threshold.title": "Adaptive Gaussian",
        "node.adaptive_gaussian_threshold.body": "Limiar local ponderado",
        "node.otsu_binarization.title": "Otsu",
        "node.otsu_binarization.body": "Limiar automático",
        "node.preview.title": "Preview",
        "node.preview.body": "Saída do canvas",
        "node.preview.action.save": "Salvar preview\ncomo PNG...",
        "node.status.ready": "PRONTO",
        "node.status.wait": "ESPERA",
        "param.kernel_size": "Kernel",
        "param.crop.start_x": "Início X",
        "param.crop.start_y": "Início Y",
        "param.crop.end_x": "Fim X",
        "param.crop.end_y": "Fim Y",
        "param.clahe.clip_limit": "Limite de clip",
        "param.clahe.tile_grid_size": "Grade",
        "param.brightness_contrast.brightness": "Brilho",
        "param.brightness_contrast.contrast": "Contraste",
        "param.gabor.kernel_size": "Kernel",
        "param.gabor.sigma": "Sigma",
        "param.gabor.theta_deg": "Theta (graus)",
        "param.gabor.lambda_value": "Lambda",
        "param.gabor.gamma": "Gamma",
        "param.gabor.psi_deg": "Psi (graus)",
        "param.frequency.mode": "Modo",
        "param.frequency.mode.none": "Nenhum",
        "param.frequency.mode.low_pass": "Passa-baixa",
        "param.frequency.mode.high_pass": "Passa-alta",
        "param.frequency.mode.band_pass": "Passa-faixa",
        "param.frequency.mode.band_stop": "Rejeita-faixa",
        "param.frequency.cutoff": "Corte",
        "param.frequency.band_min": "Faixa mín",
        "param.frequency.band_max": "Faixa máx",
        "param.grayscale.exclude_red": "Excluir vermelho",
        "param.grayscale.exclude_green": "Excluir verde",
        "param.grayscale.exclude_blue": "Excluir azul",
        "param.sobel.axis": "Eixo",
        "param.sobel.axis.x_axis": "Eixo X",
        "param.sobel.axis.y_axis": "Eixo Y",
        "param.sobel.axis.xy_axis": "Eixos XY",
        "param.global_threshold.threshold": "Limiar",
        "param.global_threshold.invert": "Inverter",
        "startup.title": "Iniciar um Projeto",
        "startup.subtitle": "Crie um novo grafo ou abra uma pipeline .ctxp existente.",
        "startup.new_project": "Novo Projeto",
        "startup.open_project": "Abrir Projeto...",
        "startup.close": "Fechar",
        "startup.version": "Versão {version}",
        "startup.select_theme": "Tema",
        "startup.select_language": "Idioma preferido",
        "startup.continue": "Entrar",
        "startup.wait": "Carregando componentes...",
        "startup.auto_continue": "Pronto. Abrindo automaticamente...",
        "startup.click_continue": "Pronto. Clique em entrar para abrir o app.",
        "startup.step.preferences": "Carregando preferências",
        "startup.step.theme": "Aplicando tema",
        "startup.step.locale": "Aplicando idioma",
        "startup.step.workspace": "Montando interface",
        "startup.ready": "Tudo pronto",
    },
}


def translate(locale_code: str, key: str, **kwargs) -> str:
    template = (
        TRANSLATIONS.get(locale_code, {}).get(key)
        or TRANSLATIONS[FALLBACK_LOCALE].get(key)
        or key
    )
    return template.format(**kwargs)


class LocalizationController(QObject):
    localeChanged = pyqtSignal(str)

    def __init__(self, initial_locale: str = DEFAULT_LOCALE) -> None:
        super().__init__()
        self._locale = DEFAULT_LOCALE
        self.set_locale(initial_locale)

    @property
    def locale(self) -> str:
        return self._locale

    def available_locales(self) -> tuple[str, ...]:
        return SUPPORTED_LOCALES

    def set_locale(self, locale_code: str) -> None:
        if locale_code not in SUPPORTED_LOCALES:
            locale_code = FALLBACK_LOCALE
        if locale_code == self._locale:
            return
        self._locale = locale_code
        self.localeChanged.emit(locale_code)

    def tr(self, key: str, **kwargs) -> str:
        return translate(self._locale, key, **kwargs)
